### PR TITLE
Fix distored collection items search view

### LINKED ISSUE #361: Distorted item view display for RDCP collection
### Descriptive summary

If using this URL to get to the item view display for the Southern Ocean Carbon and Climate Observations and Modeling collection, the item display is skewed starting from the third object down:

https://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=bb4473712z

### Steps to reproduce the behavior

- Go to DC Home Page and enter the ARK (bb4473712z)
- Note that you are taken to a results page that lists the collection record + items
- This odd display does not happen when you are in the collection record and you click on the View Items

### To Do

@VivianChu will ingest this collection onto the staging environment to better troubleshoot.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #361  ; refs #361 

Fix distorted item view display issue for RDCP collection

Changes proposed in this pull request:
* Remove the embedded html tags from the note field
* Add fixture files and test

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - please review.  
Here's the screen shot of the search result locally after removing the embedded html tags.
note_strip_tag

File: spec/features/dams_collections_spec.rb [hunk 1]
```diff
@@ -302,4 +302,45 @@
...
+    solr_index (@soccomObj3.pid)       
+  end
+  after do
+    @aCollection.delete
+    @unit.delete
+    @soccomObj1.delete
+    @soccomObj2.delete
+    @soccomObj3.delete
+  end 
+  scenario 'should see the collection item result page with correct indentation' do
```
Comment (mcritchlow) [inline spec/features/dams_collections_spec.rb]: Given the change to strip the html tags, I'm wondering if that's what this test should be more focused on. It's less about correct indentation (the side-effect) and more about assuring that any fields that we'd display as highlights in the search results don't contain html tags, is that right? I'm not sure if there's a more efficient way to test that specifically, off the top of my head, but maybe we should rename the scenario line?
